class Medecin{
  String nom;
  String prenom;
  String sex;
  String specialite;
  String adresse;
  String commune;
  String wilaya;
  String numeroTel;
  String adresseMail;
  List<String> jourTravail;
  String horaireOuverture;
  String horaireFermeture;
  String urlPhoto;

  Medecin({this.nom, this.prenom, this.sex, this.specialite, this.adresse, this.commune,
           this.wilaya, this.numeroTel, this.adresseMail, this.jourTravail, this.horaireOuverture,
           this.horaireFermeture, this.urlPhoto});

}


List<Medecin> listMedecin =[
  Medecin(
    nom: 'BOUCHEKIR',
    prenom: 'Redouane',
    sex:'M',
    specialite: 'Traumato-orthopédiste pédiatrique',
    adresse: 'PONT ALBIN LOTISSEMENT H 06 N° 131 HAI BOUAMAMA',
    commune: 'Oran',
    wilaya: 'Oran',
    numeroTel: '(041)-36-69-71',
    adresseMail: 'bouchekir.redouane@airalgerie.dz',
    jourTravail: ['1','2','3','4','5'],
    horaireOuverture: '08:00',
    horaireFermeture: '17:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom2',
    prenom: 'Prenom2',
    sex:'M',
    specialite: 'Specialite2',
    adresse: 'adresse2',
    commune: 'commune2',
    wilaya: 'wilaya2',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail2',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom3',
    prenom: 'Prenom3',
    sex:'M',
    specialite: 'Specialite3',
    adresse: 'adresse3',
    commune: 'commune3',
    wilaya: 'wilaya3',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail3',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),


  Medecin(
    nom: 'Nom4',
    prenom: 'Prenom4',
    sex:'M',
    specialite: 'Specialite4',
    adresse: 'adresse4',
    commune: 'commune4',
    wilaya: 'wilaya4',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail4',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),


  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),


  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),


  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),


  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),


  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),


  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),


  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),


  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),

  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),
  Medecin(
    nom: 'Nom5',
    prenom: 'Prenom5',
    sex:'M',
    specialite: 'Specialite5',
    adresse: 'adresse5',
    commune: 'commune5',
    wilaya: 'wilaya5',
    numeroTel: '021-20-20-30',
    adresseMail: 'adresseMail5',
    jourTravail: ['1','2','3','4','5','6','7'],
    horaireOuverture: '08:00',
    horaireFermeture: '16:00',
    urlPhoto: null,
  ),


];

